### ISSUE TITLE
IfBraceChecker doubleLineAllowed property is confusing

### ISSUE THREAD

**Issue by diogodadalt** [scalastyle/scalastyle.github.com#5]
The doubleLineAllowed property could lead to misinterpretations. One could think that this allows the following if code:
if (bool_expression)
  expression
else
  expression

when instead is allowing: 
if (bool_expression) expression
else expression

To avoid this kinds of misunderstandings the documentation should provide examples.

**Comment by matthewfarwell** [comment]
Yup. Agreed.

**Comment by diogodadalt** [comment]
This pull request is intended to address this issue: https://github.com/scalastyle/scalastyle.github.com/issues/5

**Comment by matthewfarwell** [comment]
Fixed by https://github.com/scalastyle/scalastyle/pull/131
